version: '3'

networks:
  sde:
    external: true

services:
  front-end:
    build: .
    ports:
      - 8888:80
    restart: on-failure
    networks:
      - sde
    volumes:
      - type: bind
        source: ./src
        target: /usr/share/nginx/html

